name: Get Maven 3.9.6 Temurin 17 Image

on:
  workflow_dispatch:

jobs:
  get-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Maven image
        run: |
          docker pull --disable-content-trust maven:3.9.6-eclipse-temurin-17

      - name: Save image to tar
        run: |
          docker save maven:3.9.6-eclipse-temurin-17 -o maven-3.9.6-eclipse-temurin-17.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-3.9.6-eclipse-temurin-17
          path: maven-3.9.6-eclipse-temurin-17.tar
