name: Build with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-17
    steps:
      - uses: actions/checkout@v4
      - run: mvn -v
      - run: mvn package
